# Basic conf
set -g prefix C-Space # tmux-sensible automatically unbinds C-b, and other stuff
set -a terminal-features "tmux-256color:RGB"
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g mode-keys vi

# Copy mode with vim keys
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Visual
set -g status-position top
set -g @catppuccin_window_status_style "rounded"
set -g status-left-length 100
set -g status-left "[#S]"
set -g status-right-length 100
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{tmux_mode_indicator}"

# for image.nvim
set -gq allow-passthrough on
set -g visual-activity off

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
set -g @plugin '27medkamal/tmux-session-wizard'

set -g @vim_navigator_mapping_left "M-h"
set -g @vim_navigator_mapping_right "M-l"
set -g @vim_navigator_mapping_up "M-k"
set -g @vim_navigator_mapping_down "M-j"
# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

set -g @open 'x'
set -g @open-editor 'C-x'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$HOME/.config/tmux/plugins/tpm/tpm'
